autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
nopager: false
notifications: true
parsing: true
path: ~/sync/vault/password-store
safecontent: false
mounts:
    xt6: /Users/carlos/Sync/Vault/password-store-xt6
