# List of source directories to backup.
source_directories:
    - /Users/carlos/Documents/Thunderbird

exclude_patterns:
  - '*.config/borg*'
  - '*/filterlog.html'
  - 'filterlog.html'


remote_path: /usr/local/bin/borg1/borg1
local_path: /opt/homebrew/bin/borg

archive_name_format: '{hostname}-thunderbird-{now}'

match_archives: sh:*thunderbird*

encryption_passphrase: 'cocoliso123'

# Cleanup hooks
commands:
    - before: action
      when: [create]
      run: 
         - echo "1. Borrando los filterlog"
         - find /Users/carlos/Documents/Thunderbird -type f -name 'filterlog.html' -delete -print

# Paths of local or remote repositories to backup to.
repositories:
    - path: /Volumes/BACKUPS2/Backups/homes.mac
      label: external.ssd
    - path: /Volumes/FOOTAGE/Backups/merlion
      label: external.footage
    - path: ssh://fserver7.in.xt6.us/./Backups/home.macs
      label: remote.fserver7
    - path: /Volumes/SeagateXp01/Backups/homes.macs
      label: external.seagatexp01        
      # bsd_flags: false
    - path: /Volumes/G-DRIVE-ArmorATD/backups/borg/homes.macs
      label: external.armoratd
    - path: ssh://de2162@de2162.rsync.net/./backups/home.macs.small
      label: remote.rsync.net      
      # bsd_flags: false
    - path: /Volumes/SSK Drive/Backups/borg/homes.macs
      label: external.ssk

relocated_repo_access_is_ok: true

# Retention policy for how many backups to keep.
keep_daily: 7
keep_weekly: 4
keep_monthly: 6
